#7959 Upgrade to Selenium 4 (from 3.x) (#8145)
* #7959 Upgrade to Selenium 4 (from 3.x) - what´s currently failing

* #7959 remove "w3c" = false for ChromeDriver

* #7959 replace deprecated WebDriverWait-instantiating

* #7959 temporarily disable parallel test execution

* #7959 access to browser-log on Firefox still WIP

* add custom JUnit-5 strategy to fix Selenium 4 concurrency issues for Java9+

* Selenium 4.1.1

* Updated to Selenium 4.1.2

* MinimumRunnable=0 (does it help for Java17?)

* revert MinimumRunnable

* java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap.of since Selenium 4.1.2?

* MinimumRunnable=0; second try

* resolve guava-clash between org.seleniumhq.selenium and com.googlecode.owasp-java-html-sanitizer

* fix Schedule001Test#testDateSelect for Selenium 4

* disable parallel execution for java 8 via maven-profile

* disable parallel execution for java 8 via maven-profile

* disable parallel execution for java 8 via maven-profile

* active parallel execution for java >= 9 via maven-profile

* playing around with profile-activation triggered by jdk-version

* playing around with profile-activation triggered by jdk-version

* playing around with profile-activation triggered by jdk-version

* maven debug output

* activation-jdk for single JDK

* enable/disable parallel via build.yml

* shorten parallel-execution-profile

* cleanup

Co-authored-by: Melloware <mellowaredev@gmail.com>